version: '3.9'

services:
  redis:
    container_name: 'redis'
    image: redislabs/redismod:preview
    ports:
      - 6379:6379
  redis-test:
    container_name: 'redis-test'
    image: redislabs/redismod:preview
    ports:
      - 6380:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
